# Generated by Django 3.2.9 on 2022-08-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSourceDBLastFetchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offices', models.DateTimeField()),
                ('users', models.DateTimeField()),
                ('employee_records', models.DateTimeField()),
                ('nisponno_records', models.DateTimeField()),
                ('user_login_history', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='employeerecords',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nisponnorecords',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='offices',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userloginhistory',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
