# Generated by Django 3.2.9 on 2022-08-11 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automate_process', '0002_auto_20220811_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksourcedblastfetchtime',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
