# Generated by Django 3.2.9 on 2022-08-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automate_process', '0003_tracksourcedblastfetchtime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracksourcedblastfetchtime',
            options={'ordering': ['-id']},
        ),
    ]
