# Generated by Django 3.2.9 on 2022-08-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate_process', '0004_alter_tracksourcedblastfetchtime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksourcedblastfetchtime',
            name='employee_records',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracksourcedblastfetchtime',
            name='nisponno_records',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracksourcedblastfetchtime',
            name='offices',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracksourcedblastfetchtime',
            name='user_login_history',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracksourcedblastfetchtime',
            name='users',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
