# Generated by Django 3.2.9 on 2022-09-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate_process', '0006_tracksourcedblastfetchtime_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_office_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_nisponno_records_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_hisroty_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
