# Generated by Django 3.2.9 on 2021-11-24 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.PositiveSmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_office', models.PositiveIntegerField(blank=True, null=True)),
                ('nispotti_krito_nothi', models.PositiveIntegerField(blank=True, null=True)),
                ('total_upokarvogi', models.PositiveIntegerField(blank=True, null=True)),
                ('total_users', models.PositiveIntegerField(blank=True, null=True)),
                ('total_nothi_users_male', models.PositiveIntegerField(blank=True, null=True)),
                ('total_nothi_users_female', models.PositiveIntegerField(blank=True, null=True)),
                ('total_mobile_app_users', models.PositiveIntegerField(blank=True, null=True)),
                ('total_nisponno', models.PositiveIntegerField(blank=True, null=True)),
                ('total_potrojari', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monthly_report.monthmodel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_full_year', to='monthly_report.yearmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportmodel',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='year_month'),
        ),
    ]
