# Generated by Django 3.2.9 on 2021-11-24 06:12

from django.db import migrations, models
import django.db.models.deletion
import monthly_report.models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0002_reporttypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDrilldownJSONDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=monthly_report.models.gdjd_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_report.reporttypemodel')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
