# Generated by Django 3.2.9 on 2022-01-17 05:44

from django.db import migrations, models
import django.db.models.deletion
import monthly_report.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_report', '0004_tablenamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=monthly_report.models.file_upload_path)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monthly_report.tablenamemodel')),
            ],
        ),
    ]
