# Generated by Django 3.2.9 on 2022-02-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttotalofficesmodel',
            name='report_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
