# Generated by Django 3.2.9 on 2022-02-03 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0002_reporttotalofficesmodel_report_day'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reporttotalofficesmodel',
            table='report_total_offices',
        ),
    ]
