# Generated by Django 3.2.9 on 2022-03-07 09:08

import dashboard_generate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_generate', '0015_reportloginfemalelusersmodel_reportloginmalelusersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.JSONField(default=dashboard_generate.models.empty_dictionary)),
                ('update_start_time', models.DateTimeField(blank=True, null=True)),
                ('update_completion_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_update_log',
            },
        ),
    ]
