# Generated by Django 3.2.9 on 2022-03-23 11:41

import dashboard_generate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_generate', '0017_auto_20220313_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistoryGraphsDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_hour_map', models.JSONField(default=dashboard_generate.models.EMPTY_DICTIONARY)),
                ('report_generate_time', models.DateTimeField(auto_now_add=True)),
                ('report_update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_history_graphs_data',
                'ordering': ['-id'],
            },
        ),
    ]
