# Generated by Django 3.2.9 on 2022-03-23 16:24

import dashboard_generate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0018_loginhistorygraphsdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistorygraphsdatamodel',
            name='office_login_map',
            field=models.JSONField(default=dashboard_generate.models.EMPTY_DICTIONARY),
        ),
    ]
