# Generated by Django 3.2.9 on 2022-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0019_loginhistorygraphsdatamodel_office_login_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardupdatelog',
            name='completion_log',
            field=models.CharField(default='previous log', max_length=200),
            preserve_default=False,
        ),
    ]
