# Generated by Django 3.2.9 on 2022-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0020_dashboardupdatelog_completion_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttotalofficesmodel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reporttotalofficesmodel',
            name='report_day',
        ),
        migrations.RemoveField(
            model_name='reporttotalofficesmodel',
            name='year_month_day',
        ),
        migrations.AlterField(
            model_name='reporttotalofficesmodel',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
