# Generated by Django 3.2.9 on 2022-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0021_auto_20220811_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLoginTotalUsersNotDistinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveIntegerField(db_index=True)),
                ('day', models.PositiveIntegerField(db_index=True)),
                ('counts', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('office_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'report_login_total_users_not_distinct',
            },
        ),
    ]
