# Generated by Django 3.2.9 on 2022-09-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0026_reportmobileappusersmodel_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportnispottikrittonothimodel',
            name='office_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
