# Generated by Django 3.2.9 on 2022-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0028_reportupokarvogimodel_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpotrojarimodel',
            name='office_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
