# Generated by Django 3.2.9 on 2022-09-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0030_reportnotenisponnomodel_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportandroidusersmodel',
            name='office_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportiosusersmodel',
            name='office_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
