# Generated by Django 3.2.9 on 2022-09-21 12:33

import dashboard_generate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_generate', '0031_auto_20220919_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_office_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_nisponno_records_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_history_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.JSONField(default=dashboard_generate.models.EMPTY_DICTIONARY)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
