# Generated by Django 3.2.9 on 2022-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_source_db', '0002_trackbackupdblastfetchtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupemployeerecords',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='backupnisponnorecords',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='backupoffices',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='backupuserloginhistory',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='backupusers',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='backupemployeerecords',
            name='source_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backupnisponnorecords',
            name='source_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backupoffices',
            name='source_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backupuserloginhistory',
            name='source_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backupusers',
            name='source_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
