# Generated by Django 3.2.9 on 2022-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_source_db', '0003_auto_20220912_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDBLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_office_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_nisponno_records_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_history_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
